spring:
  output:
    ansi:
      enabled: ALWAYS

  profiles:
    active: local

  batch:
    job:
      names: ${job.name:NONE}
#      parameters:
#        batch-date: '2020-01-01'

logging:
  level:
#    org.springframework.batch: debug
    org.hibernate.SQL: debug # SQL 로그 레벨
    org.hibernate.type.descriptor.sql.BasicBinder: trace # SQL 파라미터 바인딩 값을 로그에 출력
#    org.springframework.transaction: TRACE # 트랜잭션 로그 확인

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/batch_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: batch
    password: batch

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always

---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    database: h2